/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.sql.*;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Formatter;
import javax.swing.DefaultComboBoxModel;
import java.util.Date;
import java.util.regex.Matcher; 
import java.util.regex.Pattern; 
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick C
 */
public class Menu extends javax.swing.JFrame {
    Conexion con = new Conexion();
    static Statement st;
    static ResultSet rs;
    
    int cantFilas;
    int cantColumnas;

    Connection cn = (Connection) con.conexionbd();
    
    //Variables For User Creation and access
    //Prototypes
    int contadorUsers=0;
    int locationUserRecord=0;
    int searcher=0;
    boolean enter =false;
    boolean IDFound = false;
    int IDClient=0;
    String firstName[]=new String[30];
    String middleName[]=new String[30];
    String fLastName[]=new String[30];
    String sLastName[]=new String[30];
    String address[]=new String[200];
    String email[]=new String[50];
    String password[]=new String[50];
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearUserOnline = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_idClient = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_firstNameClient = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_middleNameClient = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_lastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_secondLastNameClient = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_addressClient = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_emailClient = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pf_passClient = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        pf_confirmPass = new javax.swing.JPasswordField();
        jb_acceptRecord = new javax.swing.JButton();
        rb_noEmail = new javax.swing.JRadioButton();
        rb_withEmail = new javax.swing.JRadioButton();
        jd_registradora = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        tf_clientSearch_Store = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table_Store_Client_Trans = new javax.swing.JTable();
        jb_Exit_Store_Client_Locator = new javax.swing.JButton();
        jb_searchStorePerClient = new javax.swing.JButton();
        jd_Administer = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jb_clientes_admin = new javax.swing.JButton();
        jb_InventarioTienda = new javax.swing.JButton();
        jb_comprasxclient = new javax.swing.JButton();
        jb_exit = new javax.swing.JButton();
        jb_canasta = new javax.swing.JButton();
        jf_onlineShop = new javax.swing.JFrame();
        jf_clientes = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Clients = new javax.swing.JTable();
        tf_search_id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jb_searchID = new javax.swing.JButton();
        jb_delete = new javax.swing.JButton();
        jb_exit_clients = new javax.swing.JButton();
        jf_Inventario = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        tf_tiendaID = new javax.swing.JTextField();
        jb_searchID_store = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Inventory_store = new javax.swing.JTable();
        jb_confirmExit_Inventory = new javax.swing.JButton();
        jf_compras_canasta = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_productsPerClient = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        tf_clientID_searchProducts = new javax.swing.JTextField();
        jb_searchClientProducts = new javax.swing.JButton();
        jb_exit_clientProducts = new javax.swing.JButton();
        jTF_user = new javax.swing.JTextField();
        pf_password_user = new javax.swing.JPasswordField();
        jb_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jb_register = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 3, 24)); // NOI18N
        jLabel4.setText("Registro Online");

        jLabel5.setText("ID");

        jLabel6.setText("Primer Nombre");

        jLabel7.setText("Segundo Nombre");

        jLabel8.setText("Primer Apellido");

        jLabel9.setText("Segundo Apellido");

        jLabel10.setText("Direccion");

        jLabel11.setText("E-mail");

        tf_emailClient.setText("example@rly.nc");

        jLabel12.setText("Password");

        jLabel13.setText("Confirm Password");

        jb_acceptRecord.setText("Accept");
        jb_acceptRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_acceptRecordMouseClicked(evt);
            }
        });

        rb_noEmail.setText("Sin correo");
        rb_noEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_noEmailMouseClicked(evt);
            }
        });

        rb_withEmail.setText("Con correo");
        rb_withEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_withEmailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearUserOnlineLayout = new javax.swing.GroupLayout(jd_crearUserOnline.getContentPane());
        jd_crearUserOnline.getContentPane().setLayout(jd_crearUserOnlineLayout);
        jd_crearUserOnlineLayout.setHorizontalGroup(
            jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tf_idClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                                .addComponent(tf_firstNameClient)))))
                                .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(34, 34, 34))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                        .addComponent(tf_middleNameClient))))
                            .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pf_confirmPass)
                                    .addComponent(tf_secondLastNameClient)
                                    .addComponent(tf_addressClient)
                                    .addComponent(tf_emailClient)
                                    .addComponent(pf_passClient)))))
                    .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jb_acceptRecord))
                    .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rb_noEmail)
                        .addGap(48, 48, 48)
                        .addComponent(rb_withEmail)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jd_crearUserOnlineLayout.setVerticalGroup(
            jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_idClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_firstNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_middleNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_secondLastNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tf_addressClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(tf_emailClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pf_passClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pf_confirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_noEmail)
                    .addComponent(rb_withEmail))
                .addGap(50, 50, 50)
                .addComponent(jb_acceptRecord)
                .addContainerGap())
        );

        jLabel20.setText("Client");

        Table_Store_Client_Trans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tienda", "Address"
            }
        ));
        jScrollPane4.setViewportView(Table_Store_Client_Trans);

        jb_Exit_Store_Client_Locator.setText("Exit");
        jb_Exit_Store_Client_Locator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_Exit_Store_Client_LocatorMouseClicked(evt);
            }
        });

        jb_searchStorePerClient.setText("Search");
        jb_searchStorePerClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_searchStorePerClientMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_registradoraLayout = new javax.swing.GroupLayout(jd_registradora.getContentPane());
        jd_registradora.getContentPane().setLayout(jd_registradoraLayout);
        jd_registradoraLayout.setHorizontalGroup(
            jd_registradoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registradoraLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jd_registradoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_registradoraLayout.createSequentialGroup()
                        .addComponent(tf_clientSearch_Store, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jb_searchStorePerClient))
                    .addComponent(jLabel20))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registradoraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_Exit_Store_Client_Locator)
                .addGap(140, 140, 140))
        );
        jd_registradoraLayout.setVerticalGroup(
            jd_registradoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registradoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jd_registradoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_clientSearch_Store, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_searchStorePerClient))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Exit_Store_Client_Locator)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel14.setText("Admin");

        jb_clientes_admin.setText("Clientes");
        jb_clientes_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_clientes_adminMouseClicked(evt);
            }
        });

        jb_InventarioTienda.setText("Inventario");
        jb_InventarioTienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_InventarioTiendaMouseClicked(evt);
            }
        });

        jb_comprasxclient.setText("Transacciones Realizadas");
        jb_comprasxclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_comprasxclientMouseClicked(evt);
            }
        });

        jb_exit.setText("Salir");
        jb_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_exitMouseClicked(evt);
            }
        });

        jb_canasta.setText("Canasta");
        jb_canasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_canastaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_AdministerLayout = new javax.swing.GroupLayout(jd_Administer.getContentPane());
        jd_Administer.getContentPane().setLayout(jd_AdministerLayout);
        jd_AdministerLayout.setHorizontalGroup(
            jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdministerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_exit)
                    .addGroup(jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_AdministerLayout.createSequentialGroup()
                            .addGroup(jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jd_AdministerLayout.createSequentialGroup()
                                    .addComponent(jb_clientes_admin)
                                    .addGap(32, 32, 32)
                                    .addComponent(jb_InventarioTienda))
                                .addComponent(jLabel14))
                            .addGap(18, 18, 18)
                            .addComponent(jb_comprasxclient))
                        .addComponent(jb_canasta)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jd_AdministerLayout.setVerticalGroup(
            jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdministerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(51, 51, 51)
                .addGroup(jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_clientes_admin)
                    .addComponent(jb_InventarioTienda)
                    .addComponent(jb_comprasxclient))
                .addGap(47, 47, 47)
                .addComponent(jb_canasta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jb_exit)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jf_onlineShopLayout = new javax.swing.GroupLayout(jf_onlineShop.getContentPane());
        jf_onlineShop.getContentPane().setLayout(jf_onlineShopLayout);
        jf_onlineShopLayout.setHorizontalGroup(
            jf_onlineShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_onlineShopLayout.setVerticalGroup(
            jf_onlineShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        Table_Clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(Table_Clients);

        jLabel15.setText("Buscar");

        jb_searchID.setText("Search");
        jb_searchID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_searchIDMouseClicked(evt);
            }
        });

        jb_delete.setText("Delete");
        jb_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_deleteMouseClicked(evt);
            }
        });

        jb_exit_clients.setText("Exit");
        jb_exit_clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_exit_clientsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_clientesLayout = new javax.swing.GroupLayout(jf_clientes.getContentPane());
        jf_clientes.getContentPane().setLayout(jf_clientesLayout);
        jf_clientesLayout.setHorizontalGroup(
            jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_clientesLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jf_clientesLayout.createSequentialGroup()
                        .addComponent(tf_search_id, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jb_searchID))
                    .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jf_clientesLayout.createSequentialGroup()
                            .addComponent(jb_delete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_exit_clients))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jf_clientesLayout.setVerticalGroup(
            jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_clientesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_search_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_searchID))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_clientesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jb_delete)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_clientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_exit_clients)
                        .addGap(36, 36, 36))))
        );

        jLabel16.setText("Tienda ID");

        jb_searchID_store.setText("Search");
        jb_searchID_store.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_searchID_storeMouseClicked(evt);
            }
        });

        Table_Inventory_store.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Codigo", "Cantidad", "Precio per Producto"
            }
        ));
        jScrollPane2.setViewportView(Table_Inventory_store);

        jb_confirmExit_Inventory.setText("Exit");
        jb_confirmExit_Inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_confirmExit_InventoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_InventarioLayout = new javax.swing.GroupLayout(jf_Inventario.getContentPane());
        jf_Inventario.getContentPane().setLayout(jf_InventarioLayout);
        jf_InventarioLayout.setHorizontalGroup(
            jf_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_InventarioLayout.createSequentialGroup()
                .addGroup(jf_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_InventarioLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jf_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jf_InventarioLayout.createSequentialGroup()
                                .addComponent(tf_tiendaID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jb_searchID_store))
                            .addComponent(jLabel16)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jf_InventarioLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jb_confirmExit_Inventory)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jf_InventarioLayout.setVerticalGroup(
            jf_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_InventarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jf_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tiendaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_searchID_store))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jb_confirmExit_Inventory)
                .addGap(28, 28, 28))
        );

        jLabel17.setText("Canasta por producto");

        table_productsPerClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Precio", "Costo", "IDFactura"
            }
        ));
        jScrollPane3.setViewportView(table_productsPerClient);

        jLabel18.setText("Cliente");

        jb_searchClientProducts.setText("Search");
        jb_searchClientProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_searchClientProductsMouseClicked(evt);
            }
        });

        jb_exit_clientProducts.setText("Exit");
        jb_exit_clientProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_exit_clientProductsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_compras_canastaLayout = new javax.swing.GroupLayout(jf_compras_canasta.getContentPane());
        jf_compras_canasta.getContentPane().setLayout(jf_compras_canastaLayout);
        jf_compras_canastaLayout.setHorizontalGroup(
            jf_compras_canastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_compras_canastaLayout.createSequentialGroup()
                .addGroup(jf_compras_canastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_exit_clientProducts)
                    .addGroup(jf_compras_canastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jf_compras_canastaLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jf_compras_canastaLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(jf_compras_canastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addGroup(jf_compras_canastaLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(29, 29, 29)
                                    .addComponent(tf_clientID_searchProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(jb_searchClientProducts)))
                            .addGap(75, 75, 75))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jf_compras_canastaLayout.setVerticalGroup(
            jf_compras_canastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_compras_canastaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(6, 6, 6)
                .addGroup(jf_compras_canastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_clientID_searchProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_searchClientProducts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jb_exit_clientProducts)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_login.setText("Log in");
        jb_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_loginMouseClicked(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Unispace", 3, 36)); // NOI18N
        jLabel3.setText("Wallmart");

        jb_register.setText("Register");
        jb_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_register)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_login)
                            .addComponent(pf_password_user)
                            .addComponent(jTF_user)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_user, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_password_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addComponent(jb_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jb_register)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registerMouseClicked
        // TODO add your handling code here:
        jd_crearUserOnline.setModal(true);
        jd_crearUserOnline.pack();
        jd_crearUserOnline.setLocationRelativeTo(this);
        jd_crearUserOnline.setVisible(true);
        rb_noEmail.setSelected(true);
    }//GEN-LAST:event_jb_registerMouseClicked

    private void jb_acceptRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_acceptRecordMouseClicked
        // TODO add your handling code here:
        //Adds new Client
        try{
            //Will check if the current id is new or is already on the database
            boolean stateEmail = rb_withEmail.isSelected();
            System.out.println(stateEmail);
            String sql2 = "";
            int idg = 0;
            sql2 = "SELECT ID_CLIENTE FROM CLIENTES WHERE ID_CLIENTE=" + tf_idClient.getText();
            //System.out.println(sql2);
            st = cn.createStatement();
            rs = st.executeQuery(sql2);
            int value=0;
            while(rs.next()){
                value = rs.getInt(1);
            }
            System.out.println(value);
            if(value==Integer.parseInt(tf_idClient.getText())){//In case it already exists, a message is displayed
                JOptionPane.showMessageDialog(jd_crearUserOnline, "Error, ID existente");
            }else{
                //If email will be used
                if(stateEmail){
                    if (isValid(tf_emailClient.getText())) {//Checks if current email is an actual email
                        
                        //Validate if email is already on the database
                        String sqlQueryEmail = "";
                        sqlQueryEmail ="SELECT CORREO_CLIENTE FROM CLIENTES WHERE CORREO_CLIENTE=" + tf_idClient.getText();
                        Statement st2 = cn.createStatement();
                        ResultSet rs2 = st2.executeQuery(sqlQueryEmail);
                        String usedEmail="";
                        while(rs2.next()){
                            usedEmail = rs2.getString(7);
                        }
                        if(usedEmail.equals(tf_addressClient.getText())){//Emails must be unique too
                            JOptionPane.showMessageDialog(jd_crearUserOnline, "Correo en uso");
                        }else{
                            if(pf_passClient.getText().equals(pf_confirmPass.getText())){
                                //If all data is accepted, proceed to insert into the table
                                
                                String extractID = tf_idClient.getText();
                                //PreparedStatement allows the insertion and update of new data
                                //in the database
                                PreparedStatement pps = cn.prepareStatement("INSERT INTO CLIENTES(ID_CLIENTE, PN_CLIENTE, SN_CLIENTE, PA_CLIENTE,"
                                        + "SA_CLIENTE, DIRECCION_CLIENTE, CORREO_CLIENTE) VALUES(?,?,?,?,?,?,?)");
                                pps.setInt(1, Integer.parseInt(extractID));
                                pps.setString(2, tf_firstNameClient.getText());
                                pps.setString(3, tf_middleNameClient.getText());
                                pps.setString(4, tf_lastName.getText());
                                pps.setString(5, tf_secondLastNameClient.getText());
                                pps.setString(6, tf_addressClient.getText());
                                pps.setString(7, tf_emailClient.getText());
                                pps.executeUpdate();
                                JOptionPane.showMessageDialog(jd_crearUserOnline, "Creating data.. Please wait.");
                                PreparedStatement pps2 = cn.prepareStatement("INSERT INTO CLIENTE_ONLINE(id_cliente_cliente_online, password_cliente_online)"
                                        + " VALUES(?,?)");
                                pps2.setInt(1, Integer.parseInt(extractID));
                                pps2.setString(2, pf_confirmPass.getText());
                                pps2.executeUpdate();
                                JOptionPane.showMessageDialog(jd_crearUserOnline, "Exitosamente guardado");
                                
                                //Delete field Data
                                tf_addressClient.setText("");
                                tf_idClient.setText("");
                                tf_firstNameClient.setText("");
                                tf_middleNameClient.setText("");
                                tf_lastName.setText("");
                                tf_secondLastNameClient.setText("");
                                tf_emailClient.setText("");
                                pf_confirmPass.setText("");
                                pf_passClient.setText("");
                                jd_crearUserOnline.dispose();
                                jd_crearUserOnline.setVisible(false);
                                
                            }else{
                                JOptionPane.showMessageDialog(jd_crearUserOnline, "Revise la password");
                            }
                            
                        }
                    }else{
                        JOptionPane.showMessageDialog(jd_crearUserOnline, "Email no valido");
                    }
                }else{
                    if(pf_passClient.getText().equals(pf_confirmPass)){
                                //If all data is accepted, proceed to insert into the table
                                String extractID = tf_idClient.getText();
                                //PreparedStatement allows the insertion and update of new data
                                //in the database
                                PreparedStatement pps = cn.prepareStatement("INSERT INTO CLIENTES(ID_CLIENTE, PN_CLIENTE, SN_CLIENTE, PA_CLIENTE,"
                                        + "SA_CLIENTE, DIRECCION_CLIENTE, CORREO_CLIENTE) VALUES(?,?,?,?,?,?,?)");
                                pps.setInt(1, Integer.parseInt(extractID));
                                pps.setString(2, tf_firstNameClient.getText());
                                pps.setString(3, tf_middleNameClient.getText());
                                pps.setString(4, tf_lastName.getText());
                                pps.setString(5, tf_secondLastNameClient.getText());
                                pps.setString(6, tf_addressClient.getText());
                                pps.setString(7, tf_emailClient.getText());
                                pps.executeUpdate();
                                JOptionPane.showMessageDialog(jd_crearUserOnline, "Creating data.. Please wait.");
                                PreparedStatement pps2 = cn.prepareStatement("INSERT INTO CLIENTE_ONLINE(id_cliente_cliente_online, password_cliente_online)"
                                        + " VALUES(?,?)");
                                pps2.setInt(1, Integer.parseInt(extractID));
                                pps2.setString(2, pf_confirmPass.getText());
                                pps2.executeUpdate();
                                
                                //Delete field Data
                                tf_addressClient.setText("");
                                tf_idClient.setText("");
                                tf_firstNameClient.setText("");
                                tf_middleNameClient.setText("");
                                tf_lastName.setText("");
                                tf_secondLastNameClient.setText("");
                                tf_emailClient.setText("");
                                pf_confirmPass.setText("");
                                pf_passClient.setText("");
                                jd_crearUserOnline.dispose();
                                jd_crearUserOnline.setVisible(false);
                    }
                }//In case the email is not used
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(jd_crearUserOnline, "Error en el registro de usuario");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_acceptRecordMouseClicked

    private void rb_noEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_noEmailMouseClicked
        // TODO add your handling code here:
        rb_withEmail.setSelected(false);
        rb_noEmail.setSelected(true);
    }//GEN-LAST:event_rb_noEmailMouseClicked

    private void rb_withEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_withEmailMouseClicked
        // TODO add your handling code here:
        rb_withEmail.setSelected(true);
        rb_noEmail.setSelected(false);
    }//GEN-LAST:event_rb_withEmailMouseClicked

    private void jb_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_loginMouseClicked
        // TODO add your handling code here:
        
        //Checks if the user is an admin
        String username="";
        String password="";
        username=jTF_user.getText();
        password=pf_password_user.getText();
        System.out.println(username);
        System.out.println(password);
        if(username.equals("Test") || password=="12345"){
            JOptionPane.showMessageDialog(this, "Logging in");
            jd_Administer.setModal(true);
            jd_Administer.pack();
            jd_Administer.setLocationRelativeTo(this);
            jd_Administer.setVisible(true);
            jTF_user.setText("");
            pf_password_user.setText("");
        }else if(username!="Test"){
            //In case it is not an admin, proceed to allocate the user data
        }
    }//GEN-LAST:event_jb_loginMouseClicked

    private void jb_searchIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_searchIDMouseClicked
        // TODO add your handling code here:
        //User seeker
        try{
            String locator = "";
            locator = tf_search_id.getText();
            int convertedLocator = Integer.parseInt(locator);
            String sql2 = "";
            sql2 = "SELECT ID_CLIENTE FROM CLIENTES WHERE ID_CLIENTE=" + convertedLocator;
            st = cn.createStatement();
            rs = st.executeQuery(sql2);
            int value = 0;
            while (rs.next()) {
                value = rs.getInt(1);
            }
            //Gets the current id that the admin wants to find
            System.out.println(value);
            if(value==convertedLocator){
                String nameUser="";
                String sqlname = "SELECT * FROM CLIENTES WHERE ID_CLIENTE=" + convertedLocator;
                Statement st2 = cn.createStatement();
                ResultSet rs2 = st2.executeQuery(sqlname);
                while(rs2.next()){
                    nameUser+= rs2.getString(2);
                }
                String sqlLastName = "SELECT * FROM CLIENTES WHERE ID_CLIENTE=" + convertedLocator;
                Statement st3 = cn.createStatement();
                ResultSet rs3 = st3.executeQuery(sqlLastName);
                nameUser+=" ";
                while(rs3.next()){
                    nameUser+= rs3.getString(4);
                }
                DefaultTableModel model = (DefaultTableModel) Table_Clients.getModel();
                model.addRow(new Object[]{convertedLocator,nameUser});
            }else{
                JOptionPane.showMessageDialog(jf_clientes, "User not found");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_searchIDMouseClicked

    private void jb_clientes_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_clientes_adminMouseClicked
        // TODO add your handling code here:
        jd_Administer.dispose();
        jf_clientes.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
        jf_clientes.pack();
        jf_clientes.setLocationRelativeTo(this);
        jf_clientes.setVisible(true);
        
    }//GEN-LAST:event_jb_clientes_adminMouseClicked

    private void jb_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_deleteMouseClicked
        // TODO add your handling code here:
        try {
            int xValue = Table_Clients.getSelectedRow();
            String codex = Table_Clients.getValueAt(xValue, 0).toString();
            System.out.println(codex);
            //String sql2 = "DELETE FROM CLIENTES WHERE ID_CLIENTE=" + codex;
            //st = cn.createStatement();
            //rs = st.executeQuery(sql2);
            PreparedStatement pstmnt;
            pstmnt = cn.prepareStatement("DELETE FROM CLIENTES WHERE ID_CLIENTE=" + codex);
            pstmnt.executeUpdate();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jb_deleteMouseClicked

    private void jb_exit_clientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_exit_clientsMouseClicked
        // TODO add your handling code here:
        if(Table_Clients.getRowCount()<1){
            jf_clientes.dispose();
            jd_Administer.setModal(true);
            jd_Administer.pack();
            jd_Administer.setLocationRelativeTo(this);
            jd_Administer.setVisible(true);
        }else{
            DefaultTableModel model = (DefaultTableModel) Table_Clients.getModel();
            model.setRowCount(0);
            jf_clientes.dispose();
            jd_Administer.setModal(true);
            jd_Administer.pack();
            jd_Administer.setLocationRelativeTo(this);
            jd_Administer.setVisible(true);
        }
    }//GEN-LAST:event_jb_exit_clientsMouseClicked

    private void jb_searchID_storeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_searchID_storeMouseClicked
        // TODO add your handling code here:
        try {
            String codeStore="";
            codeStore=tf_tiendaID.getText();
            String sql2 = "";
            sql2 = "SELECT id_tienda FROM TIENDAS WHERE id_tienda="+codeStore;
            int storeIdCheck=0;
            st = cn.createStatement();
            rs = st.executeQuery(sql2);
            while(rs.next()){
                storeIdCheck= rs.getInt(1);
            }
            System.out.println(storeIdCheck);
            System.out.println(codeStore);
            if(Integer.parseInt(codeStore)==storeIdCheck){
                //DefaultTableModel model2 = (DefaultTableModel) Table_Inventory_store.getModel();
                //model2.setRowCount(0);

                
                //Start Searching for the items on the store
                ArrayList <String> productsFound = new ArrayList<String>();
                String sqlItems="";
                sqlItems = "SELECT * FROM tiendaxproducto WHERE id_tienda_TP="+codeStore;
                Statement stItems = cn.createStatement();
                ResultSet rs2 = stItems.executeQuery(sqlItems);
                while(rs2.next()){
                    int getterData = rs2.getInt(2);
                    productsFound.add(Integer.toString(getterData));
                }
                /*for (int i = 0; i < productsFound.size(); i++) {
                    System.out.println(productsFound.get(i));
                }*/
                
                ArrayList <String> quantityPerProduct = new ArrayList<String>();
                //Data 2
                String sqlItemsQuantity="";
                sqlItemsQuantity = "SELECT * FROM tiendaxproducto WHERE id_tienda_TP="+codeStore;
                Statement stItems2 = cn.createStatement();
                ResultSet rs21 = stItems2.executeQuery(sqlItemsQuantity);
                
                while(rs21.next()){
                    int getQuantity = rs21.getInt(4);
                    quantityPerProduct.add(Integer.toString(getQuantity));
                }
                
                //DATA 3
                String sqlItemsPrice="";
                sqlItemsPrice = "SELECT * FROM tiendaxproducto WHERE id_tienda_TP="+codeStore;
                Statement stItemsPrices = cn.createStatement();
                ResultSet rs22 = stItemsPrices.executeQuery(sqlItemsPrice);
                ArrayList <String> pricePerProduct = new ArrayList<String>();
                while(rs22.next()){
                    int getPrice = rs22.getInt(3);
                    pricePerProduct.add(Integer.toString(getPrice));
                }
                DefaultTableModel model = (DefaultTableModel) Table_Inventory_store.getModel();
                for(int i=0; i<productsFound.size();i++){
                    String productName="";
                    String sqlGetItemName="";
                    sqlGetItemName="Select * FROM PRODUCTOS WHERE codigo_producto="+productsFound.get(i);
                    Statement stItemName= cn.createStatement();
                    ResultSet rs3= stItemName.executeQuery(sqlGetItemName);
                    while(rs3.next()){
                        productName=rs3.getString(1);
                    }
                    
                    model.addRow(new Object[]{productName,productsFound.get(i), quantityPerProduct.get(i),
                                                pricePerProduct.get(i)});
                }
                
            }else{
                JOptionPane.showMessageDialog(jf_Inventario, "La tienda no se encontro o no existe");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_searchID_storeMouseClicked

    private void jb_InventarioTiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_InventarioTiendaMouseClicked
        // TODO add your handling code here:
        jd_Administer.dispose();
        jf_Inventario.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
        jf_Inventario.pack();
        jf_Inventario.setLocationRelativeTo(this);
        jf_Inventario.setVisible(true);
    }//GEN-LAST:event_jb_InventarioTiendaMouseClicked

    private void jb_confirmExit_InventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_confirmExit_InventoryMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table_Inventory_store.getModel();
        model.setRowCount(0);
        tf_tiendaID.setText("");
        jf_Inventario.dispose();
        jd_Administer.setModal(true);
        jd_Administer.pack();
        jd_Administer.setLocationRelativeTo(this);
        jd_Administer.setVisible(true);
    }//GEN-LAST:event_jb_confirmExit_InventoryMouseClicked

    private void jb_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_exitMouseClicked
        // TODO add your handling code here:
        jd_Administer.dispose();
        
    }//GEN-LAST:event_jb_exitMouseClicked

    private void jb_canastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_canastaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_productsPerClient.getModel();
        model.setRowCount(0);
        jd_Administer.dispose();
        jf_compras_canasta.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
        jf_compras_canasta.pack();
        jf_compras_canasta.setLocationRelativeTo(this);
        jf_compras_canasta.setVisible(true);
    }//GEN-LAST:event_jb_canastaActionPerformed

    private void jb_searchClientProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_searchClientProductsMouseClicked
        // TODO add your handling code here:
        try {
            String locator = "";
            locator = tf_clientID_searchProducts.getText();
            int convertedLocator = Integer.parseInt(locator);
            String sql2 = "";
            sql2 = "SELECT ID_CLIENTE FROM CLIENTES WHERE ID_CLIENTE=" + convertedLocator;
            st = cn.createStatement();
            rs = st.executeQuery(sql2);
            int value = 0;
            while (rs.next()) {
                value = rs.getInt(1);
            }
            if(value==convertedLocator){
                String sqlGetAllItems="";
                sqlGetAllItems="SELECT id_cliente_PC FROM productoxcliente WHERE id_cliente_PC ="+value;
                Statement st2 = cn.createStatement();
                ResultSet rs2 = st2.executeQuery(sqlGetAllItems);
                
                int idValue=0;
                while(rs2.next()){
                    idValue= rs2.getInt(1);
                }
                if(idValue==value){
                    ArrayList<String> productIDs = new ArrayList<String>();
                    ArrayList <String> productNames = new ArrayList<String>();
                    ArrayList<String> quantities = new ArrayList<String>();
                    ArrayList<String> cost= new ArrayList<String>();
                    ArrayList<String> price = new ArrayList<String>();
                    String sqlGetter = "SELECT * FROM productoxcliente WHERE id_cliente_PC ="+value;
                    Statement st3 = cn.createStatement();
                    ResultSet rs3 = st3.executeQuery(sqlGetter);
                    ArrayList<String> idFactura = new ArrayList<String>();
                    while(rs3.next()){
                            idFactura.add(Integer.toString(rs3.getInt(3)));
                            productIDs.add(Integer.toString(rs3.getInt(2)));
                            quantities.add(rs3.getString(4));
                    }
                    
                    
                    for (int i = 0; i < productIDs.size(); i++) {
                        String productExtractor="";
                        productExtractor = "SELECT * FROM PRODUCTOS WHERE codigo_producto ="+productIDs.get(i);
                        Statement st4 = cn.createStatement();
                        ResultSet rst1 = st4.executeQuery(productExtractor);
                        while(rst1.next()){
                            productNames.add(rst1.getString(1));
                            price.add(Integer.toString(rst1.getInt(5)));
                            cost.add(Integer.toString(
                                    Integer.parseInt(quantities.get(i))*rst1.getInt(5)));
                        }
                    }
                    //tf_idFactura.setText(idFactura);
                    for (int i = 0; i < productIDs.size(); i++) {
                        DefaultTableModel model = (DefaultTableModel) table_productsPerClient.getModel();
                        model.addRow(new Object[]{productNames.get(i),quantities.get(i), price.get(i),
                                                cost.get(i), idFactura.get(i)});
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(jf_compras_canasta, "This client has no cart");
                }
            }else{
                JOptionPane.showMessageDialog(jf_compras_canasta, "No se encontro el cliente");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_searchClientProductsMouseClicked

    private void jb_exit_clientProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_exit_clientProductsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_productsPerClient.getModel();
        model.setRowCount(0);
        jf_compras_canasta.dispose();
        jd_Administer.setModal(true);
        jd_Administer.pack();
        jd_Administer.setLocationRelativeTo(this);
        jd_Administer.setVisible(true);
    }//GEN-LAST:event_jb_exit_clientProductsMouseClicked

    private void jb_searchStorePerClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_searchStorePerClientMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelS = (DefaultTableModel) Table_Store_Client_Trans.getModel();
        modelS.setRowCount(0);
        try{
            String compareID = tf_clientSearch_Store.getText();
            String sql2 = "";
            sql2 = "SELECT ID_CLIENTE FROM CLIENTES WHERE ID_CLIENTE=" + compareID;
            st = cn.createStatement();
            rs = st.executeQuery(sql2);
            int valueExtracted=0;
            while(rs.next()){
                valueExtracted=rs.getInt(1);
            }
            if (valueExtracted==Integer.parseInt(compareID)) {
                String sqlStores = "SELECT * FROM clientextienda WHERE id_cliente_clientextienda="+valueExtracted;
                Statement stStore = cn.createStatement();
                ResultSet rs2 = stStore.executeQuery(sqlStores);
                ArrayList<String> data = new ArrayList<String>();
                while(rs2.next()){
                    data.add(Integer.toString(rs2.getInt(2)));
                }
                ArrayList<String> locations = new ArrayList<String>();
                
                for (int i = 0; i < data.size(); i++) {
                    String sqlLocations = "SELECT * FROM TIENDAS WHERE id_tienda="+data.get(i);
                    Statement stLocations = cn.createStatement();
                    ResultSet rs3 = stLocations.executeQuery(sqlLocations);
                    while(rs3.next()){
                        locations.add(rs3.getString(3));
                    }
                }
                
                DefaultTableModel model = (DefaultTableModel) Table_Store_Client_Trans.getModel();
                
                for (int i = 0; i < data.size(); i++) {
                    model.addRow(new Object[]{data.get(i), locations.get(i)});
                }
                
            }else{
                JOptionPane.showMessageDialog(jd_registradora, "User not found");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jb_searchStorePerClientMouseClicked

    private void jb_comprasxclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_comprasxclientMouseClicked
        // TODO add your handling code here:
        jd_Administer.dispose();
        jd_registradora.setModal(true);
        jd_registradora.pack();
        jd_registradora.setLocationRelativeTo(this);
        jd_registradora.setVisible(true);
    }//GEN-LAST:event_jb_comprasxclientMouseClicked

    private void jb_Exit_Store_Client_LocatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_Exit_Store_Client_LocatorMouseClicked
        // TODO add your handling code here:
        jd_registradora.dispose();
        jd_Administer.setModal(true);
        jd_Administer.pack();
        jd_Administer.setLocationRelativeTo(this);
        jd_Administer.setVisible(true);
    }//GEN-LAST:event_jb_Exit_Store_Client_LocatorMouseClicked

    public static boolean isValid(String email) 
    { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    } 
    
    public void Connect(){
        //Connection with the Database 
        try {
            
            Statement st = cn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Clients;
    private javax.swing.JTable Table_Inventory_store;
    private javax.swing.JTable Table_Store_Client_Trans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTF_user;
    private javax.swing.JButton jb_Exit_Store_Client_Locator;
    private javax.swing.JButton jb_InventarioTienda;
    private javax.swing.JButton jb_acceptRecord;
    private javax.swing.JButton jb_canasta;
    private javax.swing.JButton jb_clientes_admin;
    private javax.swing.JButton jb_comprasxclient;
    private javax.swing.JButton jb_confirmExit_Inventory;
    private javax.swing.JButton jb_delete;
    private javax.swing.JButton jb_exit;
    private javax.swing.JButton jb_exit_clientProducts;
    private javax.swing.JButton jb_exit_clients;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_register;
    private javax.swing.JButton jb_searchClientProducts;
    private javax.swing.JButton jb_searchID;
    private javax.swing.JButton jb_searchID_store;
    private javax.swing.JButton jb_searchStorePerClient;
    private javax.swing.JDialog jd_Administer;
    private javax.swing.JDialog jd_crearUserOnline;
    private javax.swing.JDialog jd_registradora;
    private javax.swing.JFrame jf_Inventario;
    private javax.swing.JFrame jf_clientes;
    private javax.swing.JFrame jf_compras_canasta;
    private javax.swing.JFrame jf_onlineShop;
    private javax.swing.JPasswordField pf_confirmPass;
    private javax.swing.JPasswordField pf_passClient;
    private javax.swing.JPasswordField pf_password_user;
    private javax.swing.JRadioButton rb_noEmail;
    private javax.swing.JRadioButton rb_withEmail;
    private javax.swing.JTable table_productsPerClient;
    private javax.swing.JTextField tf_addressClient;
    private javax.swing.JTextField tf_clientID_searchProducts;
    private javax.swing.JTextField tf_clientSearch_Store;
    private javax.swing.JTextField tf_emailClient;
    private javax.swing.JTextField tf_firstNameClient;
    private javax.swing.JTextField tf_idClient;
    private javax.swing.JTextField tf_lastName;
    private javax.swing.JTextField tf_middleNameClient;
    private javax.swing.JTextField tf_search_id;
    private javax.swing.JTextField tf_secondLastNameClient;
    private javax.swing.JTextField tf_tiendaID;
    // End of variables declaration//GEN-END:variables

    //Views
    
    /*
    
    View #2
    CREATE VIEW canasta_purchases
    AS Select nombre_producto, cantidad_productoxcliente, precio_producto, cantidad_productoxcliente*precio_producto as preciocanasta
    FROM Producto, productoxcliente
    WHERE codigo_producto_productoxcliente = codigo_producto
    GROUP BY id_Canasta

    View #3
    CREATE VIEW client_purchases
    AS SELECT nombre_producto, id_canasta_productoxcliente, cantidad_productoxcliente, cantidad_productoxcliente*precio_producto as preciocanasta

    FROM cliente, producto, productoxcliente
    WHERE id_Cliente = idCliente_productoxcliente AND codigo_producto = codigo_producto_productoxcliente
    GROUP BY Id_cliente, PN, PA
    
    View #4
    Create view sells
    AS Select id_Cliente, PN, PA
    FROM clientextienda, cliente
    WHERE id_cliente = id_cliente_clientextienda
    GROUP BY id_tienda_clientextienda
    */

}
