/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.sql.*;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Formatter;
import javax.swing.DefaultComboBoxModel;
import java.util.Date;

/**
 *
 * @author Erick C
 */
public class Menu extends javax.swing.JFrame {
    Conexion con = new Conexion();
    static Statement sr;
    static ResultSet rs;
    
    int cantFilas;
    int cantColumnas;

    Connection cn = (Connection) con.conexionbd();
    
    //Variables For User Creation and access
    int contadorUsers=0;
    int locationUserRecord=0;
    int searcher=0;
    boolean enter =false;
    boolean IDFound = false;
    int IDClient=0;
    String firstName[]=new String[30];
    String middleName[]=new String[30];
    String fLastName[]=new String[30];
    String sLastName[]=new String[30];
    String address[]=new String[200];
    String email[]=new String[50];
    String password[]=new String[50];
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearUserOnline = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_idClient = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_firstNameClient = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_middleNameClient = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_lastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_secondLastNameClient = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_addressClient = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_emailClient = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pf_passClient = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        pf_confirmPass = new javax.swing.JPasswordField();
        jb_acceptRecord = new javax.swing.JButton();
        jd_registradora = new javax.swing.JDialog();
        jd_Administer = new javax.swing.JDialog();
        jf_onlineShop = new javax.swing.JFrame();
        jTF_user = new javax.swing.JTextField();
        pf_password_user = new javax.swing.JPasswordField();
        jb_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jb_register = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 3, 24)); // NOI18N
        jLabel4.setText("Registro Online");

        jLabel5.setText("ID");

        jLabel6.setText("Primer Nombre");

        jLabel7.setText("Segundo Nombre");

        jLabel8.setText("Primer Apellido");

        jLabel9.setText("Segundo Apellido");

        jLabel10.setText("Direccion");

        jLabel11.setText("E-mail");

        tf_emailClient.setText("example@rly.nc");

        jLabel12.setText("Password");

        jLabel13.setText("Confirm Password");

        jb_acceptRecord.setText("Accept");
        jb_acceptRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_acceptRecordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearUserOnlineLayout = new javax.swing.GroupLayout(jd_crearUserOnline.getContentPane());
        jd_crearUserOnline.getContentPane().setLayout(jd_crearUserOnlineLayout);
        jd_crearUserOnlineLayout.setHorizontalGroup(
            jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tf_idClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                                .addComponent(tf_firstNameClient)))))
                                .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18))
                                        .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(30, 30, 30)))
                                    .addGap(4, 4, 4)
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                        .addComponent(tf_middleNameClient))))
                            .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pf_confirmPass)
                                    .addComponent(tf_secondLastNameClient)
                                    .addComponent(tf_addressClient)
                                    .addComponent(tf_emailClient)
                                    .addComponent(pf_passClient)))))
                    .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jb_acceptRecord)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jd_crearUserOnlineLayout.setVerticalGroup(
            jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_idClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_firstNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_middleNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_secondLastNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tf_addressClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(tf_emailClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pf_passClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pf_confirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jb_acceptRecord)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_registradoraLayout = new javax.swing.GroupLayout(jd_registradora.getContentPane());
        jd_registradora.getContentPane().setLayout(jd_registradoraLayout);
        jd_registradoraLayout.setHorizontalGroup(
            jd_registradoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_registradoraLayout.setVerticalGroup(
            jd_registradoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_AdministerLayout = new javax.swing.GroupLayout(jd_Administer.getContentPane());
        jd_Administer.getContentPane().setLayout(jd_AdministerLayout);
        jd_AdministerLayout.setHorizontalGroup(
            jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_AdministerLayout.setVerticalGroup(
            jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jf_onlineShopLayout = new javax.swing.GroupLayout(jf_onlineShop.getContentPane());
        jf_onlineShop.getContentPane().setLayout(jf_onlineShopLayout);
        jf_onlineShopLayout.setHorizontalGroup(
            jf_onlineShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_onlineShopLayout.setVerticalGroup(
            jf_onlineShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_login.setText("Log in");

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Unispace", 3, 36)); // NOI18N
        jLabel3.setText("Wallmart");

        jb_register.setText("Register");
        jb_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_register)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_login)
                            .addComponent(pf_password_user)
                            .addComponent(jTF_user)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_user, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_password_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addComponent(jb_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jb_register)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registerMouseClicked
        // TODO add your handling code here:
        jd_crearUserOnline.setModal(true);
        jd_crearUserOnline.pack();
        jd_crearUserOnline.setLocationRelativeTo(this);
        jd_crearUserOnline.setVisible(true);
    }//GEN-LAST:event_jb_registerMouseClicked

    private void jb_acceptRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_acceptRecordMouseClicked
        // TODO add your handling code here:
        try{
            String sql2 = "";
            int idg = 0;
            sql2 = "SELECT ID_Cliente FROM CLIENTES WHERE ID_CLiente=" + tf_idClient.getText();
            if(sql2!=""){
                JOptionPane.showMessageDialog(jd_crearUserOnline, "Error, ID existente");
            }else{
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(jd_crearUserOnline, "Error en el registro de usuario");
        }
    }//GEN-LAST:event_jb_acceptRecordMouseClicked

    public void Connect(){
        try {
            
            Statement st = cn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTF_user;
    private javax.swing.JButton jb_acceptRecord;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_register;
    private javax.swing.JDialog jd_Administer;
    private javax.swing.JDialog jd_crearUserOnline;
    private javax.swing.JDialog jd_registradora;
    private javax.swing.JFrame jf_onlineShop;
    private javax.swing.JPasswordField pf_confirmPass;
    private javax.swing.JPasswordField pf_passClient;
    private javax.swing.JPasswordField pf_password_user;
    private javax.swing.JTextField tf_addressClient;
    private javax.swing.JTextField tf_emailClient;
    private javax.swing.JTextField tf_firstNameClient;
    private javax.swing.JTextField tf_idClient;
    private javax.swing.JTextField tf_lastName;
    private javax.swing.JTextField tf_middleNameClient;
    private javax.swing.JTextField tf_secondLastNameClient;
    // End of variables declaration//GEN-END:variables
}
