/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.sql.*;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Formatter;
import javax.swing.DefaultComboBoxModel;
import java.util.Date;
import java.util.regex.Matcher; 
import java.util.regex.Pattern; 
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick C
 */
public class Menu extends javax.swing.JFrame {
    Conexion con = new Conexion();
    static Statement st;
    static ResultSet rs;
    
    int cantFilas;
    int cantColumnas;

    Connection cn = (Connection) con.conexionbd();
    
    //Variables For User Creation and access
    int contadorUsers=0;
    int locationUserRecord=0;
    int searcher=0;
    boolean enter =false;
    boolean IDFound = false;
    int IDClient=0;
    String firstName[]=new String[30];
    String middleName[]=new String[30];
    String fLastName[]=new String[30];
    String sLastName[]=new String[30];
    String address[]=new String[200];
    String email[]=new String[50];
    String password[]=new String[50];
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearUserOnline = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_idClient = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_firstNameClient = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_middleNameClient = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_lastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_secondLastNameClient = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_addressClient = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_emailClient = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pf_passClient = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        pf_confirmPass = new javax.swing.JPasswordField();
        jb_acceptRecord = new javax.swing.JButton();
        rb_noEmail = new javax.swing.JRadioButton();
        rb_withEmail = new javax.swing.JRadioButton();
        jd_registradora = new javax.swing.JDialog();
        jd_Administer = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jb_clientes_admin = new javax.swing.JButton();
        jb_InventarioTienda = new javax.swing.JButton();
        jb_comprasxclient = new javax.swing.JButton();
        jb_exit = new javax.swing.JButton();
        jf_onlineShop = new javax.swing.JFrame();
        jf_clientes = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Clients = new javax.swing.JTable();
        tf_search_id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jb_searchID = new javax.swing.JButton();
        jb_delete = new javax.swing.JButton();
        jb_exit_clients = new javax.swing.JButton();
        jf_Inventario = new javax.swing.JFrame();
        jf_compras_cliente = new javax.swing.JFrame();
        jTF_user = new javax.swing.JTextField();
        pf_password_user = new javax.swing.JPasswordField();
        jb_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jb_register = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 3, 24)); // NOI18N
        jLabel4.setText("Registro Online");

        jLabel5.setText("ID");

        jLabel6.setText("Primer Nombre");

        jLabel7.setText("Segundo Nombre");

        jLabel8.setText("Primer Apellido");

        jLabel9.setText("Segundo Apellido");

        jLabel10.setText("Direccion");

        jLabel11.setText("E-mail");

        tf_emailClient.setText("example@rly.nc");

        jLabel12.setText("Password");

        jLabel13.setText("Confirm Password");

        jb_acceptRecord.setText("Accept");
        jb_acceptRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_acceptRecordMouseClicked(evt);
            }
        });

        rb_noEmail.setText("Sin correo");
        rb_noEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_noEmailMouseClicked(evt);
            }
        });

        rb_withEmail.setText("Con correo");
        rb_withEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_withEmailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearUserOnlineLayout = new javax.swing.GroupLayout(jd_crearUserOnline.getContentPane());
        jd_crearUserOnline.getContentPane().setLayout(jd_crearUserOnlineLayout);
        jd_crearUserOnlineLayout.setHorizontalGroup(
            jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tf_idClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                                .addComponent(tf_firstNameClient)))))
                                .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(34, 34, 34))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearUserOnlineLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                        .addComponent(tf_middleNameClient))))
                            .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pf_confirmPass)
                                    .addComponent(tf_secondLastNameClient)
                                    .addComponent(tf_addressClient)
                                    .addComponent(tf_emailClient)
                                    .addComponent(pf_passClient)))))
                    .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jb_acceptRecord))
                    .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rb_noEmail)
                        .addGap(48, 48, 48)
                        .addComponent(rb_withEmail)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jd_crearUserOnlineLayout.setVerticalGroup(
            jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUserOnlineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_idClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_firstNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_middleNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_secondLastNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tf_addressClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(tf_emailClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pf_passClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pf_confirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jd_crearUserOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_noEmail)
                    .addComponent(rb_withEmail))
                .addGap(50, 50, 50)
                .addComponent(jb_acceptRecord)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_registradoraLayout = new javax.swing.GroupLayout(jd_registradora.getContentPane());
        jd_registradora.getContentPane().setLayout(jd_registradoraLayout);
        jd_registradoraLayout.setHorizontalGroup(
            jd_registradoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_registradoraLayout.setVerticalGroup(
            jd_registradoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel14.setText("Admin");

        jb_clientes_admin.setText("Clientes");
        jb_clientes_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_clientes_adminMouseClicked(evt);
            }
        });

        jb_InventarioTienda.setText("Inventario");

        jb_comprasxclient.setText("Compras Realizadas");

        jb_exit.setText("Salir");

        javax.swing.GroupLayout jd_AdministerLayout = new javax.swing.GroupLayout(jd_Administer.getContentPane());
        jd_Administer.getContentPane().setLayout(jd_AdministerLayout);
        jd_AdministerLayout.setHorizontalGroup(
            jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdministerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_AdministerLayout.createSequentialGroup()
                        .addComponent(jb_clientes_admin)
                        .addGap(32, 32, 32)
                        .addComponent(jb_InventarioTienda))
                    .addComponent(jLabel14))
                .addGap(42, 42, 42)
                .addComponent(jb_comprasxclient)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AdministerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_exit)
                .addGap(25, 25, 25))
        );
        jd_AdministerLayout.setVerticalGroup(
            jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdministerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(51, 51, 51)
                .addGroup(jd_AdministerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_clientes_admin)
                    .addComponent(jb_InventarioTienda)
                    .addComponent(jb_comprasxclient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jb_exit)
                .addContainerGap())
        );

        javax.swing.GroupLayout jf_onlineShopLayout = new javax.swing.GroupLayout(jf_onlineShop.getContentPane());
        jf_onlineShop.getContentPane().setLayout(jf_onlineShopLayout);
        jf_onlineShopLayout.setHorizontalGroup(
            jf_onlineShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_onlineShopLayout.setVerticalGroup(
            jf_onlineShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        Table_Clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(Table_Clients);

        jLabel15.setText("Buscar");

        jb_searchID.setText("Search");
        jb_searchID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_searchIDMouseClicked(evt);
            }
        });

        jb_delete.setText("Delete");
        jb_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_deleteMouseClicked(evt);
            }
        });

        jb_exit_clients.setText("Exit");
        jb_exit_clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_exit_clientsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_clientesLayout = new javax.swing.GroupLayout(jf_clientes.getContentPane());
        jf_clientes.getContentPane().setLayout(jf_clientesLayout);
        jf_clientesLayout.setHorizontalGroup(
            jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_clientesLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jf_clientesLayout.createSequentialGroup()
                        .addComponent(tf_search_id, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jb_searchID))
                    .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jf_clientesLayout.createSequentialGroup()
                            .addComponent(jb_delete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_exit_clients))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jf_clientesLayout.setVerticalGroup(
            jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_clientesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_search_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_searchID))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jf_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_clientesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jb_delete)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_clientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_exit_clients)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout jf_InventarioLayout = new javax.swing.GroupLayout(jf_Inventario.getContentPane());
        jf_Inventario.getContentPane().setLayout(jf_InventarioLayout);
        jf_InventarioLayout.setHorizontalGroup(
            jf_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_InventarioLayout.setVerticalGroup(
            jf_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jf_compras_clienteLayout = new javax.swing.GroupLayout(jf_compras_cliente.getContentPane());
        jf_compras_cliente.getContentPane().setLayout(jf_compras_clienteLayout);
        jf_compras_clienteLayout.setHorizontalGroup(
            jf_compras_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jf_compras_clienteLayout.setVerticalGroup(
            jf_compras_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_login.setText("Log in");
        jb_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_loginMouseClicked(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Unispace", 3, 36)); // NOI18N
        jLabel3.setText("Wallmart");

        jb_register.setText("Register");
        jb_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_register)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_login)
                            .addComponent(pf_password_user)
                            .addComponent(jTF_user)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_user, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_password_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addComponent(jb_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jb_register)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registerMouseClicked
        // TODO add your handling code here:
        jd_crearUserOnline.setModal(true);
        jd_crearUserOnline.pack();
        jd_crearUserOnline.setLocationRelativeTo(this);
        jd_crearUserOnline.setVisible(true);
        rb_noEmail.setSelected(true);
    }//GEN-LAST:event_jb_registerMouseClicked

    private void jb_acceptRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_acceptRecordMouseClicked
        // TODO add your handling code here:
        try{
            boolean stateEmail = rb_withEmail.isSelected();
            System.out.println(stateEmail);
            String sql2 = "";
            int idg = 0;
            sql2 = "SELECT ID_CLIENTE FROM CLIENTES WHERE ID_CLIENTE=" + tf_idClient.getText();
            //System.out.println(sql2);
            st = cn.createStatement();
            rs = st.executeQuery(sql2);
            int value=0;
            while(rs.next()){
                value = rs.getInt(1);
            }
            System.out.println(value);
            if(value==Integer.parseInt(tf_idClient.getText())){
                JOptionPane.showMessageDialog(jd_crearUserOnline, "Error, ID existente");
            }else{
                //If email will be used
                if(stateEmail){
                    if (isValid(tf_emailClient.getText())) {
                        
                        //Validate if email is already on the database
                        String sqlQueryEmail = "";
                        sqlQueryEmail ="SELECT CORREO_CLIENTE FROM CLIENTES WHERE CORREO_CLIENTE=" + tf_idClient.getText();
                        Statement st2 = cn.createStatement();
                        ResultSet rs2 = st2.executeQuery(sqlQueryEmail);
                        String usedEmail="";
                        while(rs2.next()){
                            usedEmail = rs2.getString(7);
                        }
                        if(usedEmail.equals(tf_addressClient.getText())){
                            JOptionPane.showMessageDialog(jd_crearUserOnline, "Correo en uso");
                        }else{
                            if(pf_passClient.getText().equals(pf_confirmPass.getText())){
                                String extractID = tf_idClient.getText();
                                PreparedStatement pps = cn.prepareStatement("INSERT INTO CLIENTES(ID_CLIENTE, PN_CLIENTE, SN_CLIENTE, PA_CLIENTE,"
                                        + "SA_CLIENTE, DIRECCION_CLIENTE, CORREO_CLIENTE) VALUES(?,?,?,?,?,?,?)");
                                pps.setInt(1, Integer.parseInt(extractID));
                                pps.setString(2, tf_firstNameClient.getText());
                                pps.setString(3, tf_middleNameClient.getText());
                                pps.setString(4, tf_lastName.getText());
                                pps.setString(5, tf_secondLastNameClient.getText());
                                pps.setString(6, tf_addressClient.getText());
                                pps.setString(7, tf_emailClient.getText());
                                pps.executeUpdate();
                                JOptionPane.showMessageDialog(jd_crearUserOnline, "Creating data.. Please wait.");
                                PreparedStatement pps2 = cn.prepareStatement("INSERT INTO CLIENTE_ONLINE(id_cliente_cliente_online, password_cliente_online)"
                                        + " VALUES(?,?)");
                                pps2.setInt(1, Integer.parseInt(extractID));
                                pps2.setString(2, pf_confirmPass.getText());
                                pps2.executeUpdate();
                                JOptionPane.showMessageDialog(jd_crearUserOnline, "Exitosamente guardado");
                                
                                //Delete field Data
                                tf_addressClient.setText("");
                                tf_idClient.setText("");
                                tf_firstNameClient.setText("");
                                tf_middleNameClient.setText("");
                                tf_lastName.setText("");
                                tf_secondLastNameClient.setText("");
                                tf_emailClient.setText("");
                                pf_confirmPass.setText("");
                                pf_passClient.setText("");
                                jd_crearUserOnline.dispose();
                                jd_crearUserOnline.setVisible(false);
                                
                            }else{
                                JOptionPane.showMessageDialog(jd_crearUserOnline, "Revise la password");
                            }
                            
                        }
                    }else{
                        JOptionPane.showMessageDialog(jd_crearUserOnline, "Email no valido");
                    }
                }else{
                    if(pf_passClient.getText().equals(pf_confirmPass)){
                                String extractID = tf_idClient.getText();
                                PreparedStatement pps = cn.prepareStatement("INSERT INTO CLIENTES(ID_CLIENTE, PN_CLIENTE, SN_CLIENTE, PA_CLIENTE,"
                                        + "SA_CLIENTE, DIRECCION_CLIENTE, CORREO_CLIENTE) VALUES(?,?,?,?,?,?,?)");
                                pps.setInt(1, Integer.parseInt(extractID));
                                pps.setString(2, tf_firstNameClient.getText());
                                pps.setString(3, tf_middleNameClient.getText());
                                pps.setString(4, tf_lastName.getText());
                                pps.setString(5, tf_secondLastNameClient.getText());
                                pps.setString(6, tf_addressClient.getText());
                                pps.setString(7, tf_emailClient.getText());
                                pps.executeUpdate();
                                JOptionPane.showMessageDialog(jd_crearUserOnline, "Creating data.. Please wait.");
                                PreparedStatement pps2 = cn.prepareStatement("INSERT INTO CLIENTE_ONLINE(id_cliente_cliente_online, password_cliente_online)"
                                        + " VALUES(?,?)");
                                pps2.setInt(1, Integer.parseInt(extractID));
                                pps2.setString(2, pf_confirmPass.getText());
                                pps2.executeUpdate();
                                
                                //Delete field Data
                                tf_addressClient.setText("");
                                tf_idClient.setText("");
                                tf_firstNameClient.setText("");
                                tf_middleNameClient.setText("");
                                tf_lastName.setText("");
                                tf_secondLastNameClient.setText("");
                                tf_emailClient.setText("");
                                pf_confirmPass.setText("");
                                pf_passClient.setText("");
                                jd_crearUserOnline.dispose();
                                jd_crearUserOnline.setVisible(false);
                    }
                }//In case the email is not used
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(jd_crearUserOnline, "Error en el registro de usuario");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_acceptRecordMouseClicked

    private void rb_noEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_noEmailMouseClicked
        // TODO add your handling code here:
        rb_withEmail.setSelected(false);
        rb_noEmail.setSelected(true);
    }//GEN-LAST:event_rb_noEmailMouseClicked

    private void rb_withEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_withEmailMouseClicked
        // TODO add your handling code here:
        rb_withEmail.setSelected(true);
        rb_noEmail.setSelected(false);
    }//GEN-LAST:event_rb_withEmailMouseClicked

    private void jb_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_loginMouseClicked
        // TODO add your handling code here:
        String username="";
        String password="";
        username=jTF_user.getText();
        password=pf_password_user.getText();
        System.out.println(username);
        System.out.println(password);
        if(username.equals("Test") || password=="12345"){
            JOptionPane.showMessageDialog(this, "Logging in");
            jd_Administer.setModal(true);
            jd_Administer.pack();
            jd_Administer.setLocationRelativeTo(this);
            jd_Administer.setVisible(true);
            jTF_user.setText("");
            pf_password_user.setText("");
        }else if(username!="admin"){
            System.out.println("Something");
        }
    }//GEN-LAST:event_jb_loginMouseClicked

    private void jb_searchIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_searchIDMouseClicked
        // TODO add your handling code here:
        
        try{
            String locator = "";
            locator = tf_search_id.getText();
            int convertedLocator = Integer.parseInt(locator);
            String sql2 = "";
            sql2 = "SELECT ID_CLIENTE FROM CLIENTES WHERE ID_CLIENTE=" + convertedLocator;
            st = cn.createStatement();
            rs = st.executeQuery(sql2);
            int value = 0;
            while (rs.next()) {
                value = rs.getInt(1);
            }
            System.out.println(value);
            if(value==convertedLocator){
                String nameUser="";
                String sqlname = "SELECT * FROM CLIENTES WHERE ID_CLIENTE=" + convertedLocator;
                Statement st2 = cn.createStatement();
                ResultSet rs2 = st2.executeQuery(sqlname);
                while(rs2.next()){
                    nameUser+= rs2.getString(2);
                }
                String sqlLastName = "SELECT * FROM CLIENTES WHERE ID_CLIENTE=" + convertedLocator;
                Statement st3 = cn.createStatement();
                ResultSet rs3 = st3.executeQuery(sqlLastName);
                nameUser+=" ";
                while(rs3.next()){
                    nameUser+= rs3.getString(4);
                }
                DefaultTableModel model = (DefaultTableModel) Table_Clients.getModel();
                model.addRow(new Object[]{convertedLocator,nameUser});
            }else{
                JOptionPane.showMessageDialog(jf_clientes, "User not found");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_searchIDMouseClicked

    private void jb_clientes_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_clientes_adminMouseClicked
        // TODO add your handling code here:
        jd_Administer.dispose();
        jf_clientes.setModalExclusionType(Dialog.ModalExclusionType.NO_EXCLUDE);
        jf_clientes.pack();
        jf_clientes.setLocationRelativeTo(this);
        jf_clientes.setVisible(true);
        
    }//GEN-LAST:event_jb_clientes_adminMouseClicked

    private void jb_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_deleteMouseClicked
        // TODO add your handling code here:
        try {
            int xValue = Table_Clients.getSelectedRow();
            String codex = Table_Clients.getValueAt(xValue, 0).toString();
            System.out.println(codex);
            String sql2 = "DELETE FROM CLIENTES WHERE ID_CLIENTE=" + codex;
            st = cn.createStatement();
            rs = st.executeQuery(sql2);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jb_deleteMouseClicked

    private void jb_exit_clientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_exit_clientsMouseClicked
        // TODO add your handling code here:
        if(Table_Clients.getRowCount()<1){
            jf_clientes.dispose();
            jd_Administer.setModal(true);
            jd_Administer.pack();
            jd_Administer.setLocationRelativeTo(this);
            jd_Administer.setVisible(true);
        }else{
            DefaultTableModel model = (DefaultTableModel) Table_Clients.getModel();
            model.setRowCount(0);
            jf_clientes.dispose();
            jd_Administer.setModal(true);
            jd_Administer.pack();
            jd_Administer.setLocationRelativeTo(this);
            jd_Administer.setVisible(true);
        }
    }//GEN-LAST:event_jb_exit_clientsMouseClicked

    public static boolean isValid(String email) 
    { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    } 
    
    public void Connect(){
        try {
            
            Statement st = cn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Clients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_user;
    private javax.swing.JButton jb_InventarioTienda;
    private javax.swing.JButton jb_acceptRecord;
    private javax.swing.JButton jb_clientes_admin;
    private javax.swing.JButton jb_comprasxclient;
    private javax.swing.JButton jb_delete;
    private javax.swing.JButton jb_exit;
    private javax.swing.JButton jb_exit_clients;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_register;
    private javax.swing.JButton jb_searchID;
    private javax.swing.JDialog jd_Administer;
    private javax.swing.JDialog jd_crearUserOnline;
    private javax.swing.JDialog jd_registradora;
    private javax.swing.JFrame jf_Inventario;
    private javax.swing.JFrame jf_clientes;
    private javax.swing.JFrame jf_compras_cliente;
    private javax.swing.JFrame jf_onlineShop;
    private javax.swing.JPasswordField pf_confirmPass;
    private javax.swing.JPasswordField pf_passClient;
    private javax.swing.JPasswordField pf_password_user;
    private javax.swing.JRadioButton rb_noEmail;
    private javax.swing.JRadioButton rb_withEmail;
    private javax.swing.JTextField tf_addressClient;
    private javax.swing.JTextField tf_emailClient;
    private javax.swing.JTextField tf_firstNameClient;
    private javax.swing.JTextField tf_idClient;
    private javax.swing.JTextField tf_lastName;
    private javax.swing.JTextField tf_middleNameClient;
    private javax.swing.JTextField tf_search_id;
    private javax.swing.JTextField tf_secondLastNameClient;
    // End of variables declaration//GEN-END:variables
}
